#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [ -t 1 ]; then 
  # If running in a terminal
  exec < /dev/tty && node_modules/.bin/cz --hook || true
else 
  # If not running in a terminal (e.g., Windows GUI Git client)
  node_modules/.bin/cz --hook || true
fi